# SPDX-License-Identifier: GPL-2.0

# required for overlay support

dtb-$(CONFIG_ARCH_MXC) += \
						  rbz-carrier-basic-imx8m-plus.dtb \
						  rbz-carrier-basic-imx8m-mini-lvds.dtb \
						  rbz-carrier-basic-imx8m-mini-hdmi.dtb \
						  rbz-carrier-basic-imx8m-nano.dtb \
						  rbz-carrier-basic-imx8m-nano-lvds.dtb
