# SPDX-License-Identifier: GPL-2.0

# required for overlay support

dtb-$(CONFIG_ARCH_MXC) += mod-imx8m-plus.dtb \
						  rbz-carrier-basic-imx8m-plus.dtb \
						  mod-imx8m-mini.dtb \
						  rbz-carrier-basic-imx8m-mini-lvds.dtb \
						  rbz-carrier-basic-imx8m-mini-hdmi.dtb \
